---
- hosts: 172.31.11.198
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: apace2
      state: present
    when: ansible_os_family =="Debian"
    tags: newtag

  - name: install java on RedHat 
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat" 
    tags: tag2
