---
- hosts: sampleservers
  become: yes
  vars:
   forjavau: openjdk-9-jre
   forjavaL: jdk-9.0.1_linux-x64_bin.rpm
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{forjavau}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on RedHat 
    yum:
      name: "{{forjavaL}}"
      state: present
    when: ansible_os_family =="RedHat" 
