---
- hosts: sampleservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{forjavau}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java on RedHat 
    yum:
      name: "{{forjavaL}}"
      state: present
    when: ansible_os_family =="RedHat" 
